services:
  identity-foundation-app:
    extends:
      file: identity-foundation-app/compose.yaml
      service: identity-foundation-app
  identity-foundation-account:
    extends:
      file: identity-foundation-account/compose.yaml
      service: identity-foundation-account
  identity-foundation-oathkeeper:
    image: oryd/oathkeeper@sha256:44d22a42c24ba77cea84ea1523616781d4461284b2f2f8adf6a5602a0aecd3fc
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    volumes:
      - ./identity-foundation-oathkeeper/access-rules.yaml:/secrets/oathkeeper-access-rules/access-rules.yaml
      - ./identity-foundation-oathkeeper/.oathkeeper.yaml:/home/ory/.oathkeeper.yaml
    depends_on:
      - identity-foundation-account
    ports:
      - 4455:4455
      - 4456:4456
