version: '3'
services:
  identity-foundation-poc:
    image: shikanime/identity-foundation-poc:v0.1.0
    build: .
    ports:
      - 3000:3000
  identity-foundation-poc-account:
    image: shikanime/identity-foundation-poc-account:v0.1.0
    build: account
    ports:
      - 8080:80
  oathkeeper:
    image: oryd/oathkeeper:v0.38
    depends_on:
      - account
    ports:
      - 4455:4455
      - 4456:4456
    command: serve proxy -c "/etc/ory/oathkeeper/oathkeeper.yaml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    volumes:
      - ./manifests/oathkeeper/overlays/dev/access-rules.yaml:/etc/ory/oathkeeper/access-rules.yaml
      - ./manifests/oathkeeper/overlays/dev/id_token.jwks.json:/etc/ory/oathkeeper/id_token.jwks.json
      - ./manifests/oathkeeper/overlays/dev/oathkeeper.yaml:/etc/ory/oathkeeper/oathkeeper.yaml
