services:
  identity-foundation-app:
    extends:
      file: identity-foundation-app/compose.yaml
      service: identity-foundation-app
  identity-foundation-account:
    extends:
      file: identity-foundation-account/compose.yaml
      service: identity-foundation-account
  oathkeeper:
    extends:
      file: oathkeeper/compose.yaml
      service: oathkeeper
    depends_on:
      - identity-foundation-account
    ports:
      - 4455:4455
      - 4456:4456
