services:
  app:
    image: shikanime/identity-foundation-poc:v0.1.0
    build: .
    ports:
      - 3000:3000
  account:
    image: shikanime/identity-foundation-poc-account:v0.1.0
    build: account
    ports:
      - 80:80
  oathkeeper:
    image: oryd/oathkeeper:v0.38
    depends_on:
      - account
    ports:
      - 4455:4455
      - 4456:4456
    command: serve proxy -c "/etc/ory/oathkeeper/oathkeeper.yaml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    volumes:
      - ./deploy/oathkeeper:/etc/ory/oathkeeper
