services:
  oathkeeper:
    image: oryd/oathkeeper:v0.38@sha256:44d22a42c24ba77cea84ea1523616781d4461284b2f2f8adf6a5602a0aecd3fc
    command:
      - serve
      - proxy
      - -c
      - /etc/ory/oathkeeper/oathkeeper.yaml
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    volumes:
      - ./id_token.jwks.json:/secrets/ory/oathkeeper/id_token.jwks.json
      - ./access-rules.yaml:/etc/ory/oathkeeper/access-rules.yaml
      - ./oathkeeper.yaml:/etc/ory/oathkeeper/oathkeeper.yaml
