apiVersion: v1
kind: Service
metadata:
  labels:
    app: identity-foundation-poc
  name: identity-foundation-poc
spec:
  ports:
    - name: web
      port: 3000
      targetPort: web
  selector:
    app: identity-foundation-poc
