apiVersion: v1
kind: Service
metadata:
  labels:
    app: identity-foundation-poc-account
  name: identity-foundation-poc-account
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: identity-foundation-poc-account
