apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oathkeeper
  name: oathkeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oathkeeper
  template:
    metadata:
      labels:
        app: oathkeeper
    spec:
      containers:
        - args:
            - serve
            - proxy
            - -c
            - /etc/ory/oathkeeper/oathkeeper.yaml
          image: oryd/oathkeeper:v0.38
          name: oathkeeper
          ports:
            - containerPort: 4455
              name: proxy
            - containerPort: 4456
              name: api
          resources: {}
          volumeMounts:
            - mountPath: /etc/ory/oathkeeper
              name: oathkeeper-config
              readOnly: true
      volumes:
        - name: oathkeeper-config
          configMap:
            name: oathkeeper-config
