apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - deployment-patch.yaml
configMapGenerator:
  - name: oathkeeper-config
    files:
      - id_token.jwks.json
      - access-rules.yaml
      - oathkeeper.yaml
