name: Container Images
on:
  push:
    branches:
      - main
jobs:
  docker:
    strategy:
      matrix:
        include:
          - app: account
            context: identity-foundation-account
          - app: app
            context: identity-foundation-app
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.app }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "${{ matrix.context }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
